### ISSUE TITLE
Primary key

### ISSUE THREAD

**Issue by amqex** [VinceG/PHP-DB-Migration-Class#1]
I cannot get the migration to work when using primary keys. I get the following error:

```
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'PRIMARY KEY (`id`)
) ENGINE=InnoDB' at line 5' in /lib/MySQLMigration.php:145
```

Stack trace:

```
#0 /lib/MySQLMigration.php(145): PDOStatement->execute()
#1 /migrations/m120712_145124_test.php(15): MySQLMigration->createTable('test', Array, 'ENGINE=InnoDB')
#2 /lib/Migration.php(438): m120712_145124_test->up()
#3 /lib/Migration.php(418): Migration->migrateUp('m120712_145124_...')
#4 /lib/Migration.php(177): Migration->migrationUp(Array)
#5 /migrate.php(15): Migration->start()
#6 {main}
thrown in /lib/MySQLMigration.php on line 145
```

This is what I have in the up function of my migration file:

```
public function up()
    {
            $this->createTable('test',
                    array(
                        'id' => 'int(11) NOT NULL AUTO_INCREMENT',
                        'create_time' => 'int(11) NULL DEFAULT NULL',
                        'update_time' => 'int(11) NULL DEFAULT NULL',
                        'PRIMARY KEY (`id`)',
                    ), 'ENGINE=InnoDB');
    }
```

**Comment by VinceG** [comment]
Use:

public function up()
    {
            $this->createTable('test',
                    array(
                        'id' => 'int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT',
                        'create_time' => 'int(11) NULL DEFAULT NULL',
                        'update_time' => 'int(11) NULL DEFAULT NULL',
                    ), 'ENGINE=InnoDB');
    }

**Comment by amqex** [comment]
Nice, works great! thanks! But I also had another problem with using multiple keys. For example:

I get a Multiple primary key defined error. How can multiple keys be used?

```
public function up()
{
$this->createTable('test',
array(
'id' => 'int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT',
'user_id' => 'int(11) NOT NULL KEY',
'category => 'varchar(16) NOT NULL KEY',
'create_time' => 'int(11) NULL DEFAULT NULL',
'update_time' => 'int(11) NULL DEFAULT NULL',
), 'ENGINE=InnoDB');
}
```

**Comment by VinceG** [comment]
Try

```
public function up()
```

{
$this->createTable('test',
array(
'id' => 'int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT',
'user_id' => 'int(11) NOT NULL INDEX',
category => 'varchar(16) NOT NULL INDEX',
'create_time' => 'int(11) NULL DEFAULT NULL',
'update_time' => 'int(11) NULL DEFAULT NULL',
), 'ENGINE=InnoDB');
}

**Comment by amqex** [comment]
I tried it, but I get the following error:

```
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'INDEX,
```

**Comment by VinceG** [comment]
then just run a normal SQL query and add the indexes. Same thing.
